[project]
name = 'Blockchain-Based-Specialized-Pollinator-Habitat-Management'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.impact-assessment]
path = 'contracts/impact-assessment.clar'
clarity_version = 2
epoch = 2.5

[contracts.maintenance-protocol]
path = 'contracts/maintenance-protocol.clar'
clarity_version = 2
epoch = 2.5

[contracts.site-registration]
path = 'contracts/site-registration.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
